import 'package:flutter/material.dart';import 'package:satyashopping/core/app_export.dart';import 'package:satyashopping/widgets/app_bar/appbar_title.dart';import 'package:satyashopping/widgets/app_bar/appbar_trailing_image.dart';import 'package:satyashopping/widgets/app_bar/custom_app_bar.dart';import 'package:satyashopping/widgets/custom_elevated_button.dart';import 'package:satyashopping/widgets/custom_outlined_button.dart';import 'widgets/productcardlistorder_item_widget.dart';class MyProfileMyOrdersOrderDetailsPage extends StatelessWidget {const MyProfileMyOrdersOrderDetailsPage({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 30.v), child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 15.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildOrderDetailsHead(context), SizedBox(height: 17.v), _buildTrackingNumber(context), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("3 items", style: theme.textTheme.titleSmall)), SizedBox(height: 21.v), _buildProductCardListOrder(context), SizedBox(height: 36.v), Text("Order information", style: theme.textTheme.titleSmall), SizedBox(height: 20.v), _buildShippingAddress(context), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(left: 1.h, right: 49.h), child: Row(children: [Padding(padding: EdgeInsets.symmetric(vertical: 5.v), child: Text("Payment method:", style: CustomTextStyles.bodyMediumGray500_1)), CustomImageView(imagePath: ImageConstant.imgUserYellow800, height: 25.v, width: 32.h, margin: EdgeInsets.only(left: 12.h)), Padding(padding: EdgeInsets.only(left: 15.h, top: 4.v, bottom: 5.v), child: Text("**** **** **** 3947", style: theme.textTheme.titleSmall))])), SizedBox(height: 26.v), Padding(padding: EdgeInsets.only(left: 1.h, right: 86.h), child: Row(children: [Text("Delivery method:", style: CustomTextStyles.bodyMediumGray500_1), Padding(padding: EdgeInsets.only(left: 17.h), child: Text("FedEx, 3 days, 15", style: theme.textTheme.titleSmall))])), SizedBox(height: 28.v), _buildDiscount(context), SizedBox(height: 28.v), Row(children: [Text("Total Amount:", style: CustomTextStyles.bodyMediumGray500_1), Padding(padding: EdgeInsets.only(left: 36.h), child: Text("133", style: theme.textTheme.titleSmall))]), SizedBox(height: 37.v), _buildReorder(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 33.h, leading: Container(height: 24.v, width: 25.h, margin: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 12.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.centerLeft, margin: EdgeInsets.only(right: 1.h), onTap: () {onTapImgArrowLeft(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center, margin: EdgeInsets.only(left: 1.h), onTap: () {onTapImgArrowLeft1(context);})])), centerTitle: true, title: AppbarTitle(text: "Order Details"), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgBaselineSearch24pxGray900, margin: EdgeInsets.fromLTRB(11.h, 8.v, 11.h, 12.v))], styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildOrderDetailsHead(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Order №1947034", style: theme.textTheme.titleMedium), Text("05-12-2019", style: CustomTextStyles.bodyMediumGray500_1)]); } 
/// Section Widget
Widget _buildTrackingNumber(BuildContext context) { return Row(children: [Text("Tracking number:", style: CustomTextStyles.bodyMediumGray500_1), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("IW3475453455", style: theme.textTheme.titleSmall)), Spacer(), Text("Delivered", style: CustomTextStyles.titleSmallGreen600)]); } 
/// Section Widget
Widget _buildProductCardListOrder(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: 3, itemBuilder: (context, index) {return ProductcardlistorderItemWidget();})); } 
/// Section Widget
Widget _buildShippingAddress(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 2.v, bottom: 23.v), child: Text("Shipping Address:", style: CustomTextStyles.bodyMediumGray500_1)), Container(width: 210.h, margin: EdgeInsets.only(left: 10.h), child: Text("3 Newbridge Court ,Chino Hills, \nCA 91709, United States", maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall!.copyWith(height: 1.43)))])); } 
/// Section Widget
Widget _buildDiscount(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h, right: 32.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("Discount:", style: CustomTextStyles.bodyMediumGray500_1)), Text("10%, Personal promo code", style: theme.textTheme.titleSmall)])); } 
/// Section Widget
Widget _buildReorder(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(text: "Reorder", margin: EdgeInsets.only(right: 12.h))), Expanded(child: CustomElevatedButton(height: 36.v, text: "Leave feedback", margin: EdgeInsets.only(left: 12.h), buttonStyle: CustomButtonStyles.outlineRedFTL18))]); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft1(BuildContext context) { Navigator.pop(context); } 
 }
