import 'package:flutter/material.dart';import 'package:satyashopping/core/app_export.dart';import 'package:satyashopping/widgets/app_bar/appbar_leading_image.dart';import 'package:satyashopping/widgets/app_bar/custom_app_bar.dart';import 'package:satyashopping/widgets/custom_elevated_button.dart';class ForgotPasswordScreen extends StatelessWidget {const ForgotPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 8.h, right: 75.h), child: Column(children: [_buildAppBar(context), SizedBox(height: 31.v), Text("Forgot password", style: theme.textTheme.displaySmall)])), Container(padding: EdgeInsets.only(left: 15.h, top: 88.v, right: 15.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 332.h, margin: EdgeInsets.only(right: 12.h), child: Text("Please, enter your email address. You will receive a link to create a new password via email.", maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall!.copyWith(height: 1.43))), SizedBox(height: 16.v), _buildTextFieldOrdinaryError(context), SizedBox(height: 54.v), CustomElevatedButton(text: "SEND", margin: EdgeInsets.only(left: 1.h)), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 24.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgChevron, margin: EdgeInsets.fromLTRB(15.h, 4.v, 351.h, 4.v), onTap: () {onTapChevron(context);})); } 
/// Section Widget
Widget _buildTextFieldOrdinaryError(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 12.v), decoration: AppDecoration.outlineSecondaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Email", style: CustomTextStyles.bodySmallSecondaryContainer), SizedBox(height: 6.v), Text("email2", style: CustomTextStyles.titleSmallOnPrimaryContainer)])), CustomImageView(imagePath: ImageConstant.imgOutlineClose24px, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 6.v, right: 1.h, bottom: 5.v))])), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("Not a valid email address. Should be your@email.com", style: CustomTextStyles.bodySmallSecondaryContainer))])); } 

/// Navigates back to the previous screen.
onTapChevron(BuildContext context) { Navigator.pop(context); } 
 }
