import 'package:flutter/material.dart';import 'package:satyashopping/core/app_export.dart';import 'package:satyashopping/widgets/app_bar/appbar_leading_image.dart';import 'package:satyashopping/widgets/app_bar/appbar_title.dart';import 'package:satyashopping/widgets/app_bar/appbar_trailing_image.dart';import 'package:satyashopping/widgets/app_bar/custom_app_bar.dart';import 'widgets/catalogtwo_item_widget.dart';import 'widgets/productcard_item_widget.dart';class CatalogTwoPage extends StatelessWidget {const CatalogTwoPage({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [_buildCatalog(context), SizedBox(height: 16.v), SizedBox(height: 548.v, width: 342.h, child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Text("17", style: theme.textTheme.titleSmall))), Align(alignment: Alignment.bottomRight, child: Padding(padding: EdgeInsets.only(right: 138.h), child: Text("21", style: CustomTextStyles.titleSmallGray500))), Align(alignment: Alignment.bottomRight, child: Padding(padding: EdgeInsets.only(right: 111.h), child: Text("14", style: CustomTextStyles.titleSmallPrimary))), _buildProductCard(context)]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 12.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitle(text: "Women’s tops"), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgBaselineSearch24pxGray900, margin: EdgeInsets.fromLTRB(11.h, 8.v, 11.h, 12.v))], styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildCatalog(BuildContext context) { return SizedBox(height: 90.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Container(height: 90.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), boxShadow: [BoxShadow(color: appTheme.black900.withOpacity(0.12), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 4))]))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.fromLTRB(16.h, 56.v, 16.h, 10.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgBaselineFilterList24px, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 7.h, top: 5.v, bottom: 7.v), child: Text("Filters", style: CustomTextStyles.bodySmallGray900)), Spacer(flex: 48), CustomImageView(imagePath: ImageConstant.imgBaselineSwapVert24px, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h, top: 6.v, bottom: 6.v), child: Text("Price: lowest to high", style: CustomTextStyles.bodySmallGray900)), Spacer(flex: 51), CustomImageView(imagePath: ImageConstant.imgViewGray900, height: 24.v, width: 21.h)]))), Align(alignment: Alignment.topCenter, child: SizedBox(height: 90.v, child: ListView.separated(padding: EdgeInsets.only(left: 16.h, top: 8.v, bottom: 52.v), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 7.h);}, itemCount: 4, itemBuilder: (context, index) {return CatalogtwoItemWidget();})))])); } 
/// Section Widget
Widget _buildProductCard(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(bottom: 6.v), child: GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 263.v, crossAxisCount: 2, mainAxisSpacing: 18.h, crossAxisSpacing: 18.h), physics: NeverScrollableScrollPhysics(), itemCount: 4, itemBuilder: (context, index) {return ProductcardItemWidget();}))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
